adding app.yaml 9

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -34,7 +34,7 @@ jobs:
           ls -R
           pwd
           echo "Checking .do/app.yaml:"
-          ls -la .do/app.yaml || echo "ERROR: File missing"
+          ls -la ./app.yaml || echo "ERROR: File missing"
       - name: Update DigitalOcean App with new image
         run: |
           doctl apps update ${{ secrets.DIGITALOCEAN_APP_ID }} \
